### ISSUE TITLE
[BUG] - The conda lock file for jupyterlab is severely outdated

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/nebari-docker-images#116]
### Describe the bug

When perusing the repository content I noticed that the [jupyterlab/conda-linux-64.lock](https://github.com/nebari-dev/nebari-docker-images/blob/main/jupyterlab/conda-linux-64.lock) lock file has way older versions of packages compared to `environment.yaml` and was not updated in last 2 years.

### Expected behavior

The lock file might function to alert of security vulnerabilities in older versions so it could be a good idea to keep it in the repo, but there should be a way to auto-update it. In short term it could be simply dropped to avoid confusion.

### How to Reproduce the problem?

Open https://github.com/nebari-dev/nebari-docker-images/blob/main/jupyterlab/conda-linux-64.lock

**Comment by pavithraes** [comment]
Thanks for catching this!

Yes, it was added when QHub was migrated to Nebari, and has never been updated since. I agree we can remove it for now, and open a new issue to auto-generate lockfiles for all other integrations (jupyterlab, jupyterhub, dask, etc.)
