### ISSUE TITLE
Build docker images for GPU: nvidia/cuda

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari-docker-images#16]
### Context

At the moment installing and running GPU based libraries is quite tricky and doesn't always works as expected. Installing them manually on the base ubuntu image isn't a great idea, that's why it would be great to build gpu images with base as [nvidia/cuda](https://hub.docker.com/r/nvidia/cuda)

Relevant issue: https://github.com/Quansight/qhub/issues/1378

### Value and/or benefit

Nvidia drivers would be installed properly and Installing GPU libraries would be trivial.

Although there are many `nvidia:cuda` base images people would want to use, but it would be great to at least provided one basic jupyterlab and dask-worker image with nvidia-drivers installed.

**Comment by viniciusdc** [comment]
I loved the addition from #17, I can also add some testing for the new GPU-based images. Is there something important that we want to make sure that the built image has? e.g a module, driver, something I could write a test for :smile:
