### ISSUE TITLE
Add release instructions to `nebari-dev/docker-images`

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-docker-images#43]
🏷  agreed tagging `date-branch-shortSha-mainVersion` - note` mainVersion` e.g. for JupyterHub image - would be JupyterHub version - like for [Jupyter Docker Stacks](https://hub.docker.com/layers/scipy-notebook/jupyter/scipy-notebook/notebook-6.4.12/images/sha256-5059eead486f6c05e8d229757eb8101ecc4abdd653589993f25c9441521ec446?context=explore))

**Comment by pavithraes** [comment]
We have some instructions in our docs here: https://www.nebari.dev/docs/community/maintainers/release-process-branching-strategy#nebari-docker-images

@trallard @iameskild -- Is there anything more we should add to the docs, or shall we close this issue as completed?

**Comment by iameskild** [comment]
I personally don't see anything else we need to add at this moment.
