### ISSUE TITLE
[CI] Push images to registries on PRs

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari-docker-images#87]
At the moment, we are only pushing images to the docker registry (Quay) when the PR is merged ([here](https://github.com/nebari-dev/nebari-docker-images/blob/57ceb79f1d466bcd4dff4ad7e0a69359436d739b/.github/workflows/build-push-docker.yaml#L8-L23)). This means there is no simple way of test/use these images without first merging the PR (or as I have done in the past, modify the CI to push on PRs and reverse, those changes after we've confirmed these images are working as expected.

**Comment by pavithraes** [comment]
Thanks for this issue, I think this is a useful update to make :)

**Comment by iameskild** [comment]
I will investigate what the cost associated with this change might be. 

Another option is to add the option to push but disable it by default -- needs investigating.

**Comment by marcelovilla** [comment]
I'm closing this issue as [currently images are being built and pushed to quay on every commit of a given PR/branch](https://github.com/nebari-dev/nebari-docker-images/blob/main/.github/workflows/build-push-docker.yaml#L8-L10).
